# Common configuration templates using YAML anchors

# Base service configuration
x-service-base: &service-base
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 2G
        cpus: "2.0"
      reservations:
        memory: 1G
        cpus: "1.0"
  networks:
    - config

# Health check configurations (test parameter set per service)
x-healthcheck: &healthcheck
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 60s

# Traefik labels - web specific
x-traefik-web: &traefik-web
  - "traefik.enable=true"
  - "traefik.http.routers.dungeons-dragons.rule=Host(`dnd.localtest.me`)"
  - "traefik.http.routers.dungeons-dragons.entrypoints=websecure"
  - "traefik.http.routers.dungeons-dragons.tls=true"
  - "traefik.http.services.dungeons-dragons.loadbalancer.server.port=3000"


x-volume-node-modules: &volume-node-modules
  type: volume
  target: /app/node_modules

services:
  dungeons-dragons:
    container_name: dungeons-dragons
    <<: *service-base
    labels: *traefik-web
    build:
      context: .
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - <<: *volume-node-modules
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      <<: *healthcheck

networks:
  config:
    external: true

