// What SRD 5.2.1 says the data layer must contain.
//
// These are content assertions, not unit tests of behaviour: the data is
// generated by `scripts/srd/build-srd-data.mjs` from an upstream that has been
// wrong before (nine weapon rows, one condition sentence, two species sizes),
// so every value this file names was read off the SRD 5.2.1 PDF by hand. A
// regeneration that quietly picks upstream's number back up fails here.
//
// The other half of the job is licensing: SRD 5.2.1 publishes exactly twelve
// classes with exactly one subclass each, nine species and four backgrounds.
// The count assertions are the guard against a thirteenth subclass — which
// would not be CC-BY — arriving with a future regeneration.
import { BACKGROUNDS } from './backgrounds'
import { CLASSES, SUBCLASSES, subclassesForClass } from './classes'
import { CONDITIONS } from './conditions'
import { ORIGIN_FEATS } from './feats'
import { SPECIES } from './species'
import { WEAPONS, WEAPON_MASTERIES, WEAPON_PROPERTIES } from './weapons'

describe('SRD 5.2.1 content boundaries', () => {
  it('publishes the nine SRD species and no others', () => {
    expect(SPECIES.indexes).toEqual([
      'dragonborn',
      'dwarf',
      'elf',
      'gnome',
      'goliath',
      'halfling',
      'human',
      'orc',
      'tiefling',
    ])
  })

  it('does not carry the species SRD 5.2.1 dropped or never licensed', () => {
    for (const index of ['half-elf', 'half-orc', 'aasimar']) {
      expect(SPECIES.has(index)).toBe(false)
    }
  })

  it('publishes the four SRD backgrounds', () => {
    expect(BACKGROUNDS.indexes).toEqual(['acolyte', 'criminal', 'sage', 'soldier'])
  })

  it('publishes the twelve SRD classes and no Artificer', () => {
    expect(CLASSES.indexes).toEqual([
      'barbarian',
      'bard',
      'cleric',
      'druid',
      'fighter',
      'monk',
      'paladin',
      'ranger',
      'rogue',
      'sorcerer',
      'warlock',
      'wizard',
    ])
    expect(CLASSES.has('artificer')).toBe(false)
  })

  it('publishes exactly one subclass per class — the CC-BY boundary', () => {
    expect(SUBCLASSES.all).toHaveLength(12)
    for (const characterClass of CLASSES.all) {
      expect(subclassesForClass(characterClass.index)).toHaveLength(1)
    }
  })

  it('names the twelve subclasses SRD 5.2.1 licenses', () => {
    const byClass = Object.fromEntries(
      CLASSES.all.map((entry) => [entry.index, subclassesForClass(entry.index)[0].name]),
    )
    expect(byClass).toEqual({
      barbarian: 'Path of the Berserker',
      bard: 'College of Lore',
      cleric: 'Life Domain',
      druid: 'Circle of the Land',
      fighter: 'Champion',
      monk: 'Warrior of the Open Hand',
      paladin: 'Oath of Devotion',
      ranger: 'Hunter',
      rogue: 'Thief',
      sorcerer: 'Draconic Sorcery',
      warlock: 'Fiend Patron',
      wizard: 'Evoker',
    })
  })

  it('publishes the fifteen conditions, Exhaustion among them', () => {
    expect(CONDITIONS.all).toHaveLength(15)
    expect(CONDITIONS.has('exhaustion')).toBe(true)
  })

  it('publishes the four Origin feats a background can grant', () => {
    expect(ORIGIN_FEATS.indexes).toEqual(['alert', 'magic-initiate', 'savage-attacker', 'skilled'])
  })

  it('publishes the eight weapon mastery properties', () => {
    expect(WEAPON_MASTERIES.indexes).toEqual([
      'cleave',
      'graze',
      'nick',
      'push',
      'sap',
      'slow',
      'topple',
      'vex',
    ])
  })

  it('publishes the ten weapon properties', () => {
    expect(WEAPON_PROPERTIES.all).toHaveLength(10)
  })
})

describe('species', () => {
  it('grants no ability score increases — 2024 moved those to the background', () => {
    for (const species of SPECIES.all) {
      expect(species).not.toHaveProperty('abilityScores')
    }
  })

  it('records the two species whose size the SRD leaves to the player', () => {
    expect(SPECIES.get('human')?.size).toBe('Medium or Small')
    expect(SPECIES.get('tiefling')?.size).toBe('Medium or Small')
    expect(SPECIES.get('dwarf')?.size).toBe('Medium')
  })

  it('gives the Goliath the SRD 35-foot speed', () => {
    expect(SPECIES.get('goliath')?.speed).toBe(35)
    expect(SPECIES.get('halfling')?.speed).toBe(30)
  })

  it('gives every species at least one trait, with text', () => {
    for (const species of SPECIES.all) {
      expect(species.traits.length).toBeGreaterThan(0)
      for (const trait of species.traits) expect(trait.description.length).toBeGreaterThan(0)
    }
  })
})

describe('backgrounds', () => {
  it('grants three abilities, an Origin feat, two skills and a tool', () => {
    for (const background of BACKGROUNDS.all) {
      expect(background.abilityScores).toHaveLength(3)
      expect(new Set(background.abilityScores).size).toBe(3)
      expect(ORIGIN_FEATS.has(background.originFeat.index)).toBe(true)
      expect(background.skillProficiencies).toHaveLength(2)
      expect(background.toolProficiency).not.toBeNull()
    }
  })

  it('matches the SRD Acolyte row', () => {
    const acolyte = BACKGROUNDS.get('acolyte')
    expect(acolyte?.abilityScores).toEqual(['intelligence', 'wisdom', 'charisma'])
    expect(acolyte?.originFeat).toEqual({
      index: 'magic-initiate',
      name: 'Magic Initiate',
      note: 'Cleric',
    })
    expect(acolyte?.skillProficiencies).toEqual(['insight', 'religion'])
    expect(acolyte?.toolProficiency?.name).toBe("Calligrapher's Supplies")
  })

  it('matches the SRD Soldier row, including the tool the SRD leaves as a choice', () => {
    const soldier = BACKGROUNDS.get('soldier')
    expect(soldier?.abilityScores).toEqual(['strength', 'dexterity', 'constitution'])
    expect(soldier?.originFeat.index).toBe('savage-attacker')
    expect(soldier?.skillProficiencies).toEqual(['athletics', 'intimidation'])
    expect(soldier?.toolProficiency).toEqual({
      index: 'gaming-set',
      name: 'Gaming Set',
      note: 'Choose one kind of Gaming Set',
    })
  })

  it('carries the SRD starting-equipment line for every background', () => {
    for (const background of BACKGROUNDS.all) {
      expect(background.equipment).toHaveLength(1)
      expect(background.equipment[0]).toMatch(/^Choose A or B: /)
    }
  })
})

describe('classes', () => {
  it('gives every class its subclass at level 3 — the 2024 uniform rule', () => {
    for (const characterClass of CLASSES.all) {
      expect(characterClass.subclassLevel).toBe(3)
    }
  })

  it('matches the SRD hit dice', () => {
    const hitDice = Object.fromEntries(CLASSES.all.map((entry) => [entry.index, entry.hitDie]))
    expect(hitDice).toEqual({
      barbarian: 12,
      bard: 8,
      cleric: 8,
      druid: 8,
      fighter: 10,
      monk: 8,
      paladin: 10,
      ranger: 10,
      rogue: 8,
      sorcerer: 6,
      warlock: 8,
      wizard: 6,
    })
  })

  it('matches the SRD saving throw proficiencies', () => {
    expect(CLASSES.get('fighter')?.savingThrows).toEqual(['strength', 'constitution'])
    expect(CLASSES.get('wizard')?.savingThrows).toEqual(['intelligence', 'wisdom'])
    for (const characterClass of CLASSES.all) {
      expect(characterClass.savingThrows).toHaveLength(2)
    }
  })

  it('keeps subclass features off the class — a Fighter is not a Champion', () => {
    const fighterFeatureNames =
      CLASSES.get('fighter')?.features.map((feature) => feature.name) ?? []
    expect(fighterFeatureNames).toContain('Second Wind')
    expect(fighterFeatureNames).not.toContain('Improved Critical')
    expect(SUBCLASSES.get('champion')?.features.map((feature) => feature.name)).toContain(
      'Improved Critical',
    )
  })

  it('gives the Rogue four skill choices and the Fighter two', () => {
    expect(CLASSES.get('rogue')?.skillChoices[0].choose).toBe(4)
    expect(CLASSES.get('fighter')?.skillChoices[0].choose).toBe(2)
  })
})

describe('weapons', () => {
  it('publishes the SRD table in full: 38 weapons across four sections', () => {
    expect(WEAPONS.all).toHaveLength(38)
    const sections = WEAPONS.all.reduce<Record<string, number>>((counts, weapon) => {
      const key = `${weapon.category}-${weapon.kind}`
      counts[key] = (counts[key] ?? 0) + 1
      return counts
    }, {})
    expect(sections).toEqual({
      'simple-melee': 10,
      'simple-ranged': 4,
      'martial-melee': 18,
      'martial-ranged': 6,
    })
  })

  it('gives every weapon exactly one mastery property that resolves', () => {
    for (const weapon of WEAPONS.all) {
      expect(WEAPON_MASTERIES.has(weapon.mastery)).toBe(true)
    }
  })

  it('resolves every weapon property to a defined one', () => {
    for (const weapon of WEAPONS.all) {
      for (const property of weapon.properties) {
        expect(WEAPON_PROPERTIES.has(property)).toBe(true)
      }
    }
  })

  // The nine rows where upstream disagreed with the SRD 5.2.1 Weapons table.
  // Each expectation is the printed value; if one of these fails, the
  // generator's WEAPON_CORRECTIONS table has stopped applying.
  it.each([
    ['dart', { quantity: 5, unit: 'cp' }],
    ['hand-crossbow', { quantity: 75, unit: 'gp' }],
    ['javelin', { quantity: 5, unit: 'sp' }],
    ['longbow', { quantity: 50, unit: 'gp' }],
    ['spear', { quantity: 1, unit: 'gp' }],
  ])('prices the %s as the SRD table does', (index, cost) => {
    expect(WEAPONS.get(index as string)?.cost).toEqual(cost)
  })

  it.each([
    ['hand-crossbow', 3],
    ['mace', 4],
    ['pike', 18],
    ['spear', 3],
    ['sling', null],
  ])('weighs the %s as the SRD table does', (index, weight) => {
    expect(WEAPONS.get(index as string)?.weight).toBe(weight)
  })

  it('deals the SRD damage for the Sling and the Trident', () => {
    expect(WEAPONS.get('sling')?.damage).toEqual({ dice: '1d4', type: 'bludgeoning' })
    expect(WEAPONS.get('trident')?.damage).toEqual({ dice: '1d8', type: 'piercing' })
    expect(WEAPONS.get('trident')?.twoHandedDamage).toEqual({ dice: '1d10', type: 'piercing' })
  })

  it('matches the SRD Longsword row', () => {
    const longsword = WEAPONS.get('longsword')
    expect(longsword).toMatchObject({
      category: 'martial',
      kind: 'melee',
      damage: { dice: '1d8', type: 'slashing' },
      twoHandedDamage: { dice: '1d10', type: 'slashing' },
      properties: ['versatile'],
      mastery: 'sap',
      weight: 3,
      cost: { quantity: 15, unit: 'gp' },
    })
  })
})

describe('conditions', () => {
  it('quotes the SRD Charmed wording, not a paraphrase of it', () => {
    expect(CONDITIONS.get('charmed')?.description).toContain(
      'The charmer has Advantage on any ability check to interact with you socially.',
    )
  })

  it('describes 2024 Exhaustion as a cumulative penalty to D20 Tests', () => {
    const exhaustion = CONDITIONS.get('exhaustion')?.description ?? ''
    expect(exhaustion).toContain('the roll is reduced by 2 times your Exhaustion level')
    expect(exhaustion).toContain('You die if your Exhaustion level is 6.')
  })

  it('gives every condition text', () => {
    for (const condition of CONDITIONS.all) {
      expect(condition.description.length).toBeGreaterThan(0)
    }
  })
})
