// The sheet's slice of the equipment and magic-item data
// (`triage/sheet-bundle-srd-json`).
//
// The character sheet is the page opened on a phone mid-fight, and its
// inventory rule needs four small facts out of two large collections: which
// indexes are magic rather than mundane, the magic-item names a custom row can
// be typed as, what the seven packs unfold into, and what the SRD calls each
// equipment row. Importing `MAGIC_ITEMS` and `EQUIPMENT` for them put ~340 KB
// of raw JSON in the sheet's client bundle; this is the same four facts in
// ~26 KB.
//
// Generated by `scripts/srd/sheet-inventory.mjs` as part of a data
// regeneration, purely derived from the two collections — no upstream call and
// no correction of its own. `sheet-inventory.test.ts` asserts it still agrees
// with them, so a regeneration that changes a name or a pack and leaves this
// behind fails CI.
import sheetInventoryData from './data/sheet-inventory.json'

/** One line of a pack's contents, as the data carries it. */
export interface SheetInventoryPackContent {
  index: string
  /** The equipment name, or `null` for a content index the collection lacks. */
  name: string | null
  quantity: number
}

export interface SheetInventoryData {
  /** Indexes the magic-item collection has and the mundane equipment one does not. */
  magicOnlyIndexes: string[]
  /** Every magic-item name, already lowered. */
  magicItemNames: string[]
  /** The SRD name of every equipment row, keyed by index. */
  equipmentNames: Record<string, string>
  /** Contents by pack index, for the seven equipment rows that have any. */
  packs: Record<string, SheetInventoryPackContent[]>
}

const data = sheetInventoryData as SheetInventoryData

/**
 * Indexes that are magic by reference.
 *
 * `shield` is the one index both collections carry — the generic magic parent
 * of `+1 Shield` and the plain 2 gp shield share it — so it is deliberately
 * absent here and a cleric's shield stays mundane.
 */
export const MAGIC_ONLY_INDEXES: ReadonlySet<string> = new Set(data.magicOnlyIndexes)

/**
 * The 262 magic-item names, lowered, so a custom row typed as "cloak of
 * protection" counts the same as one typed with capitals.
 */
export const MAGIC_ITEM_NAMES: ReadonlySet<string> = new Set(data.magicItemNames)

/**
 * What the SRD calls each of the 182 equipment rows, keyed by index — so an
 * inventory row names a `priests-pack` the way the Library does, "Priest's
 * Pack" rather than the index's own words.
 *
 * Every weapon is an equipment row too, so one map covers the whole vocabulary
 * a stored `equipmentIndex` can be drawn from. A `Map` rather than the plain
 * object the JSON carries, for the same reason as {@link PACK_CONTENTS}.
 */
export const EQUIPMENT_NAMES: ReadonlyMap<string, string> = new Map(
  Object.entries(data.equipmentNames),
)

/**
 * What each equipment pack holds, keyed by the pack's index.
 *
 * A `Map` rather than the plain object the JSON carries: the key looked up is
 * a stored `equipmentIndex`, and an index of `constructor` must miss rather
 * than answer with something off `Object.prototype`.
 */
export const PACK_CONTENTS: ReadonlyMap<string, readonly SheetInventoryPackContent[]> = new Map(
  Object.entries(data.packs),
)
