CREATE TABLE "characters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" text NOT NULL,
	"name" text NOT NULL,
	"class_index" text NOT NULL,
	"species_index" text NOT NULL,
	"level" smallint DEFAULT 1 NOT NULL,
	"strength" smallint DEFAULT 10 NOT NULL,
	"dexterity" smallint DEFAULT 10 NOT NULL,
	"constitution" smallint DEFAULT 10 NOT NULL,
	"intelligence" smallint DEFAULT 10 NOT NULL,
	"wisdom" smallint DEFAULT 10 NOT NULL,
	"charisma" smallint DEFAULT 10 NOT NULL,
	"max_hit_points" integer NOT NULL,
	"current_hit_points" integer NOT NULL,
	"temporary_hit_points" integer DEFAULT 0 NOT NULL,
	"armor_class" smallint DEFAULT 10 NOT NULL,
	"speed" smallint DEFAULT 30 NOT NULL,
	"spell_slots" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"conditions" text[] DEFAULT '{}'::text[] NOT NULL,
	"death_save_successes" smallint DEFAULT 0 NOT NULL,
	"death_save_failures" smallint DEFAULT 0 NOT NULL,
	"known_spell_indexes" text[] DEFAULT '{}'::text[] NOT NULL,
	"prepared_spell_indexes" text[] DEFAULT '{}'::text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "characters_level_range" CHECK ("characters"."level" between 1 and 20),
	CONSTRAINT "characters_strength_range" CHECK ("characters"."strength" between 1 and 30),
	CONSTRAINT "characters_dexterity_range" CHECK ("characters"."dexterity" between 1 and 30),
	CONSTRAINT "characters_constitution_range" CHECK ("characters"."constitution" between 1 and 30),
	CONSTRAINT "characters_intelligence_range" CHECK ("characters"."intelligence" between 1 and 30),
	CONSTRAINT "characters_wisdom_range" CHECK ("characters"."wisdom" between 1 and 30),
	CONSTRAINT "characters_charisma_range" CHECK ("characters"."charisma" between 1 and 30),
	CONSTRAINT "characters_max_hit_points_positive" CHECK ("characters"."max_hit_points" >= 1),
	CONSTRAINT "characters_current_hit_points_positive" CHECK ("characters"."current_hit_points" >= 0),
	CONSTRAINT "characters_temporary_hit_points_positive" CHECK ("characters"."temporary_hit_points" >= 0),
	CONSTRAINT "characters_armor_class_positive" CHECK ("characters"."armor_class" >= 0),
	CONSTRAINT "characters_speed_positive" CHECK ("characters"."speed" >= 0),
	CONSTRAINT "characters_death_save_successes_range" CHECK ("characters"."death_save_successes" between 0 and 3),
	CONSTRAINT "characters_death_save_failures_range" CHECK ("characters"."death_save_failures" between 0 and 3)
);
--> statement-breakpoint
CREATE INDEX "characters_owner_id_idx" ON "characters" USING btree ("owner_id");